// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FlowRate struct {
	ID        int64            `json:"id"`
	Value     float64          `json:"value"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Volume struct {
	ID        int64            `json:"id"`
	Value     float64          `json:"value"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
