// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	CreateFlowRate(ctx context.Context, arg CreateFlowRateParams) (FlowRate, error)
	CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error)
	GetVolumes(ctx context.Context, limit int32) ([]Volume, error)
	GetVolumesByPeriod(ctx context.Context, arg GetVolumesByPeriodParams) ([]GetVolumesByPeriodRow, error)
}

var _ Querier = (*Queries)(nil)
