services:
  db:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5444:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
